version: 2
jobs:
  build:
    branches:
        only:
            react
        ignore:
            master
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: git configure
          command: |
            git config user.email "kevinmariogerard@gmail.com"
            git config user.name "KevinMarioGerard"
      - run: npm run build
      - run: npm run deploy
