version: 2
jobs:
  build:
    branches:
        only:
            master
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "b0:e9:0f:a8:70:39:c5:c1:d6:db:0b:56:05:6f:fd:c8"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: git configure
          command: |
            git config user.email "kevinmariogerard@gmail.com"
            git config user.name "KevinMarioGerard"
      - run: npm run build
      - run: npm run deploy
