version: 2
jobs:
    build:
        docker:
            - image: circleci/node:11
        working_directory: ~/react-portfolio
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest'
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                name: NPM Package install
                command: npm ci
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package-lock.json" }}
            - run:
                name: Build
                command: npm run build
            - persist_to_workspace:
                  root: .
                  paths:
                      - dist/*

    deploy:
        docker:
            - image: circleci/node:11
        working_directory: ~/react-portfolio
        steps:
            - checkout
            - run:
                name: Update npm
                command: 'sudo npm install -g npm@latest' 
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package-lock.json" }}
            - add_ssh_keys:
                fingerprints:
                    - "74:c6:f8:85:5a:99:a5:87:50:e4:63:c3:f3:9a:f4:73"
            - attach_workspace:
                at: ~/react-portfolio
            - run: ls dist
            - run: 
                name: configure git
                command: |
                    git config user.email "kevinmariogerard@gmail.com"
                    git config user.name "KevinMarioGerard"
            - run:
                name: Deploy
                command: npm run deploy

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: circleci
