version: 2
jobs:
  build:
    branches:
        only:
            master
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "74:c6:f8:85:5a:99:a5:87:50:e4:63:c3:f3:9a:f4:73"
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: git configure
          command: |
            git config user.email "kevinmariogerard@gmail.com"
            git config user.name "KevinMarioGerard"
      - run: npm run build
      - run: npm run deploy
